// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "EarthWise",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "EarthWise",
            targets: ["AppModule"],
            bundleIdentifier: "marsh.Swift-Student-Challenge-v1",
            teamIdentifier: "H349G2ZH8B",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "The purpose of the camera usage is to showcase the user's carbon footprint relative to a skyscraper, using ARKit.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)